### ISSUE TITLE
Implement Blake2 hash gadget

### ISSUE THREAD

**Issue by Acentelles** [anoma/taiga#145]

**Comment by XuyangSong** [comment]
I suggest we use the halo2 native circuit system to implement the blake2 hash gadget if we want to start this issue recently.

1. I don't think importing the serialized/deserialized circuit from Vamp-IR to Taiga is manageable for now. We must handle the configuration compatibility problem and the circuit combination problem between native circuits and Vamp-IR circuits. We need to find out the difficulty and the workload.
2. Vamp-IR is using fan-in 2 gates. We need the custom gates to reduce the size of the constraints for performance consideration. Zk-garage has fan-in 3 gates; I don't know if Vamp-IR plans to support fan-in 3 Gates and custom gates.
3. Vamp-IR takes over the 50s to generate a Blake2 proof. I expect a better performance since our whole action and vp circuits only take 2~3s to generate a proof.
4. If we have a native halo2 Blake2 hash circuit, I think it would be good to compare the native Halo2 circuit and Vamp-IR.

**Comment by bazzilic** [comment]
1. My plan for the nearest time is to make this work s I plan to write circuits for the DAO app using VampIR. In general, I think that to avoid double efforts and for better compartmentalization, it makes sense that eventually everything ZK-related is abstracted from Taiga (for example through a Taiga-defined interface to a VampIR library, which already can create circuits, prove them, and verify the proofs; probably we can extract a vk using it as well).
2. I'm not sure about this details, maybe @lopeetall or @CarloModicaPortfolio can answer that.
3. 25s on my end for Halo2 (34s on an Intel). But this is just the very first iteration of integrating Halo2 into VampIR, it's not even in the main branch yet, as I understand, I believe it will get dramatically better in the nearest time.
4. It would be good to compare, true.
