### ISSUE TITLE
Implement VP which allows for a signature check over arbitrary data

### ISSUE THREAD

**Issue by simonmasson** [anoma/taiga#52]
We want to be able to sign notes.
Two options for not leaking information on the owner:
* Use randomized signatures as in Zcash
* Use ZK proofs for the verification.

**Comment by cwgoes** [comment]
Question: do we need to do anything in the Taiga architecture in order to allow for signature checks in VPs? Could be as simple as providing a partial transaction hash to each VP (which could then check a signature over it).

Order of operations: Implement the simple thing first, optimise later if and only if necessary. We could implement something with rerandomizable signatures that moves signature checks to outside the circuit (more efficient) but not yet clear if necessary.

**Comment by cwgoes** [comment]
@simonmasson are you working on this rn?

**Comment by simonmasson** [comment]
No but I think Xuyang integrated binding signatures. Is it what you are talking about? I think it is already merged into main.

**Comment by simonmasson** [comment]
I will remove myself from the assignees*

**Comment by joebebel** [comment]
I think the right thing to do is pass the hash of the partial transaction to the VP, then it can do the signature check.

Of the Schnorr variants, I think EdDSA will fit best. I'm not sure if we can use the re-randomization ability of RedPallas, but otherwise the RedPallas algorithm should work well.

**Comment by Acentelles** [comment]
Closed by #128
